server:
  port: 7003

spring:
  application:
    name:
eureka:
  instance:
    hostname: eureka-7003.com         # eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false       # 为false表示自己是注册中心
    service-url:                #监控页面
      defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/